### ISSUE TITLE
[BUG Wiki]: missing " in example code

### ISSUE THREAD

**Issue by SVNKoch** [wasi-master/sponsorblock.py#5]
### Description of the bug

The example for the add_skip_segment (https://sponsorblockpy.readthedocs.io/en/latest/api_reference.html?highlight=client#sponsorblock.client.Client.add_skip_segments)
the 5th line of the example code should start with "

### Steps To Reproduce

reading the wiki :D

**Comment by wasi-master** [comment]
I remember fixing it a while ago 🤔. Maybe I forgot to push the changes, I'll check

Yeah I [fixed it sometime ago](https://github.com/wasi-master/sponsorblock.py/commit/30a1a7bba420dceea37472bcaf86f926d7553f0b#diff-80087dbb965d1ef26aee6ee57fec3698fd0a79c3afd9c9cd3d9156788dd0892cL359-R359) maybe docs aren't updated, I'll check

**Comment by SVNKoch** [comment]
cool :+1: 

additionally in the same exmaple code block you create segment by using
`sb.Segment(..., action_type="skip")`

However the Segment Code states that this has no effect:
![grafik](https://user-images.githubusercontent.com/39488412/168328773-3565ffaa-8ae4-4d22-bf25-104116f2a171.png)
Furthermore the default value = none but you then describe that it is a skip segment. Maybe the default value should be "skip" then?

And the other options are not listed anywhere? I assume it's "mute"?
(sry ajays api wiki page is currently down due to certificate error, if these are the official values)

**Comment by wasi-master** [comment]
Yeah I'll update it tomorrow.

I believe when I wrote it the only action type was skip and mute didn’t exist yet so I didn’t specify that explicitly

**Comment by SVNKoch** [comment]
take your time. It's nothing urgent. Thank you :)

**Comment by wasi-master** [comment]
Yeah I fixed it somewhile ago in [this commit](https://github.com/wasi-master/sponsorblock.py/commit/30a1a7bba420dceea37472bcaf86f926d7553f0b#diff-80087dbb965d1ef26aee6ee57fec3698fd0a79c3afd9c9cd3d9156788dd0892cL359-R359) and even pushed it. But I forgot to add a documentation dependency so the [docs build failed](https://readthedocs.org/projects/sponsorblockpy/builds/16666510/)

It should be fixed now
