### ISSUE TITLE
[BUG]: no json header present for adding segments post request

### ISSUE THREAD

**Issue by SVNKoch** [wasi-master/sponsorblock.py#6]
### Description of the bug

I wanted to submit segments, however I got a 400 Bad Request. I then modified the client.py Code to show the error by printing `response.text` in line 391. => "No valid videoID, userID field(s) provided." But these were both valid.
After some searching: You need to send a header that declares you're sending json.

```
headers = {'Content-type': 'application/json'}
requests.post(url, data=json.dumps(body), headers=headers)
```

Or alternative you can use the `json` keyword instead of `data`

Maybe it would be a good idea to append the request.text to the raised error message so the suer knows what exactly is the problem

### Steps To Reproduce

```
import sponsorblock
client = sponsorblock.Client(user_id="my ID from the settings menu")
client.add_skip_segments(
        "https://www.youtube.com/watch?v=XYZ",
        segment=sponsorblock.Segment(category="intro", start=0, end=6.845000)
    )
```
=> 400 Bad Request

**Comment by wasi-master** [comment]
Thanks for the report, I haven’t used the sponsorblock API in the past few months so I didn’t know about the new breaking changes, I'll fix these tomorrow as it is bedtime for me where I live
